version: '3'
services:

  web:
    container_name: web
    hostname: web
    build: ./web
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    working_dir: ${APP_PATH_CONTAINER}
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ./web/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./web/vhost.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_RUN_GROUP=#1000
      - APACHE_RUN_USER=#1000
      - PATH_TO=${APP_PATH_HOST}
      - SERVER_NAME=${APP_HOST}

  db:
    container_name: db
    hostname: db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_USER: root
      MYSQL_DATABASE: itsvit
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080

  composer:
    image: composer:1.10
    volumes:
     - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install
